version: 1
disable_existing_loggers: False
formatters:
    brief:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    precise:
        format: "%(asctime)s - %(filename)s - [line:%(lineno)d] - %(levelname)s - %(message)s"
        datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: brief
        stream: ext://sys.stdout
    file:
        class: logging.handlers.TimedRotatingFileHandler
        level: INFO
        formatter: precise
        when: midnight
        filename: /home/wangli/logs/AlphaCore/log.txt
        encoding: utf8
    none:
        class: logging.NullHandler

loggers:
    clogger:
        level: DEBUG
        handlers: [console]
        propagate: False
    flogger:
        level: INFO
        handlers: [file]
        propagate: False
    elogger:
        level: WARNING
        handlers: [console, file]
        propagate: False

root:
    level: INFO
    handlers: [console, file]
